### ISSUE TITLE
NanoPi DUO2

### ISSUE THREAD

**Issue by knivd** [epsilonrt/piduino#16]
Can it be supported please?

**Comment by epsilonrt** [comment]
Hello,
For now DUO2 is not supported but just create it in the piduino database. Since DUO2 uses H3, there is no additional development to be expected.
I have a lot of work right now.
I had planned to finish [pidbm](https://github.com/epsilonrt/pidbm) before the end of the year but it seems difficult.
I plan to integrate pido the ability to manage Pi boards (listing, creation and modification), so I ask you a little patience.
